version: "3"

services:
  earnapp2mqtt:
    container_name: earnapp2mqtt
    build: ./
    restart: unless-stopped
    environment:
      - MQTT_IP=${MQTT_IP}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - USER_TOKEN=${USER_TOKEN}
